config/routes.rb
Rails.application.routes.draw do

  resource :end_users, only: [:show, :edit, :update]
  get 'end_users/leave_user'
  patch "end_users/leave" => "end_users#leave"
  root 'items#top'
  resources :items, only: [:index, :show]
  devise_for :end_users, controllers: {   
    registrations: 'end_users/registrations',
    sessions: 'end_users/sessions' 
  }
  resources :cart_items, only: [:index, :create, :update, :destroy]
  delete "cart_items" => "cart_items#all_destroy", as: 'cart_items_all_destroy'

  get "orders/end"
  resources :orders, only: [:new, :index, :create, :show]
  post "orders/check"
  resources :addresses, only: [:index, :edit, :create, :update, :destroy]

  devise_for :admin, controllers: {
    sessions: 'admin/sessions'
  }
  namespace :admin do
    get "top", :to=>"items#top"
    resources :items
    resources :end_users, only: [:index, :show, :update, :edit]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :orders, only: [:index, :update, :show] do
      resources :order_details, only: [:update]
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

    belongs_to :end_user, optional: true
    belongs_to :item, optional: true
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  def index
    @cart_items = CartItem.where(end_user_id: current_end_user.id)
  end

  def create
    @cart_item = CartItem.new(cart_item_params)
    if current_end_user.cart_items.find_by(item_id: params[:cart_item][:item_id]).present?
      @cart_present_item = current_end_user.cart_items.find_by(item_id: params[:cart_item][:item_id])
      @cart_present_item.amount = @cart_present_item.amount + @cart_item.amount
      @cart_present_item.save(cart_item_params)
      redirect_to cart_items_path
    else
      @cart_item.end_user_id = current_end_user.id
      @cart_item.save(cart_item_params)
      redirect_to cart_items_path
    end
  end

  def update
    @cart_items = CartItem.where(end_user_id: current_end_user.id)
    @cart_item = CartItem.find(params[:id])
    if @cart_item.update(cart_item_params)
      redirect_to cart_items_path
    else
      render :index
    end

  end

  def destroy
    cart_item = CartItem.find(params[:id])
    cart_item.destroy
    redirect_to cart_items_path
  end

  def all_destroy
    cart_items = CartItem.where(end_user_id: current_end_user.id)
    cart_items.destroy_all
    redirect_to cart_items_path
  end

  private
  def cart_item_params
    params.require(:cart_item).permit(:amount,:item_id)
  end

end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/views/cart_items/index.html.erb
<div class="container">
  <div class="row mt-4">
    <div class="col-3 strong">
       <h3>ショッピングカート</h3>
    </div>
    <div class="col-7"></div>
    <div class="col-2">
       <%= link_to 'カートを空にする', cart_items_all_destroy_path, method: :delete, "data-confirm" => "本当に本当にカートを空にしますか？", class: "btn btn-danger" %>
    </div>
  </div>
  <table class="table table-bordered my-3">
            <thead class="thead-light">
                <tr>
                <th>商品名</th>
                <th scope="col">単価(税込)</th>
                <th scope="col">数量</th>
                <th scope="col">小計</th>
                <th></th>
                </tr>
            </thead>
            <tbody>
            <% prices = 0 %><!-- 合計価格 -->
            <% @cart_items.each do |cart_item| %>
                <tr>
                <td style="width: 400px">
                <div class="row">
                  <div class="col-3">
                    <%= attachment_image_tag cart_item.item, :image, size: '10x60' , format: 'jpeg', class: "card-img-top", fallback: "no_image.png",size: '10x60' %>
                  </div>
                  <div class="col-9"><%= cart_item.item.name %></div>
                </div>
                </td>
                <td>
                  <% price = (cart_item.item.price_excluding_tax * 1.1).floor %><!-- 税込価格 -->
                  <%= price %>
                </td>
                <td style="width: 200px">
                    <%= form_for cart_item, url: cart_item_path(cart_item.id) do |f| %>
                    <div class="row">
                        <div class="form-group col-6">
                          <%= f.number_field :amount, autocomplete: "amount", class: 'form-control', min: 1 %>
                        </div>
                        <div class="col-6">
                          <%= f.submit "変更", class: "btn btn-info" %>
                        </div>
                    </div>
                    <% end %>
                </td>
                <td>
                    <%=  price * cart_item.amount %><!-- 小計計算 -->
                </td>
                <td style="width: 150px" class="text-center">
                  <%= link_to '削除する', cart_item_path(cart_item.id), method: :delete, class: "btn btn-danger" %>
                </td>
                </tr>
              <% prices = prices + price * cart_item.amount %><!-- 合計計算 -->
            <% end %>
            </tbody>
  </table>
  <div class="row mt-3">
    <div class="col-2">
      <%= link_to '買い物を続ける', root_path, class: "btn btn-info" %>
    </div>
    <div class="col-6"></div>
    <div class="col-4">
      <table class="table table-bordered">
        <tr>
          <td class="table-secondary">合計金額</td>
          <td>
            <%= prices %><!-- 合計金額表示 -->
            <% session[:totsl_payment] = prices %>
          </td>
        </tr>
      </table>
    </div>
  </div>
  <div class="text-center">
    <%= link_to "情報入力に進む", new_order_path, class: "btn btn-lg btn-success" %>
  </div>
</div>