config/routes.rb
Rails.application.routes.draw do

  resource :end_users, only: [:show, :edit, :update]
  get 'end_users/leave_user'
  patch "end_users/leave" => "end_users#leave"
  root 'items#top'
  resources :items, only: [:index, :show]
  devise_for :end_users, controllers: {   
    registrations: 'end_users/registrations',
    sessions: 'end_users/sessions' 
  }
  resources :cart_items, only: [:index, :create, :update, :destroy]
  delete "cart_items" => "cart_items#all_destroy", as: 'cart_items_all_destroy'

  get "orders/end"
  resources :orders, only: [:new, :index, :create, :show]
  post "orders/check"
  resources :addresses, only: [:index, :edit, :create, :update, :destroy]

  devise_for :admin, controllers: {
    sessions: 'admin/sessions'
  }
  namespace :admin do
    get "top", :to=>"items#top"
    resources :items
    resources :end_users, only: [:index, :show, :update, :edit]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :orders, only: [:index, :update, :show] do
      resources :order_details, only: [:update]
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/end_user.rb
class EndUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :kana_first_name, presence: true
  validates :kana_last_name, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true

  def active_for_authentication?
    super && (self.is_working == true)
  end

end

app/controllers/admin/end_users_controller.rb
class Admin::EndUsersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @end_users = EndUser.all
  end

  def show
    @end_user = EndUser.find(params[:id])
  end

  def edit
    @end_user = EndUser.find(params[:id])
  end

  def update
    @end_user = EndUser.find(params[:id])
    if @end_user.update(end_user_params)
      redirect_to admin_end_user_path(@end_user)
    else
      render :edit
    end
  end

  private
  def end_user_params
    params.require(:end_user).permit(:first_name, :last_name, :kana_first_name, :kana_last_name, :address, :phone_number, :postal_code, :is_working)
  end

end

app/controllers/end_users/confirmations_controller.rb
# frozen_string_literal: true

class EndUsers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/end_users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class EndUsers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/end_users/passwords_controller.rb
# frozen_string_literal: true

class EndUsers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/end_users/registrations_controller.rb
# frozen_string_literal: true

class EndUsers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  def after_sign_up_path_for(resource)
    end_users_path
  end
  
  #アカウント編集後のリダイレクト先
  def after_update_path_for(resource)
    end_users_path
  end

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/end_users/sessions_controller.rb
# frozen_string_literal: true

class EndUsers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  
  def after_sign_in_path_for(resource)
    end_users_path
  end
  
  def after_sign_out_path_for(resource)
    root_path
  end
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/end_users/unlocks_controller.rb
# frozen_string_literal: true

class EndUsers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/end_users_controller.rb
class EndUsersController < ApplicationController
  before_action :end_use_is_working
  before_action :authenticate_end_user!
  def show
    @end_user = current_end_user
  end

  def edit
    @end_user = current_end_user
  end

  def update
    @end_user = current_end_user
    if @end_user.update(end_user_params)
      redirect_to end_users_path
    else
      render :edit
    end
  end

  def leave_user
    @end_user = current_end_user
  end

  def leave
    @end_user = current_end_user
    @end_user.update(is_working: false)
    reset_session
    flash[:notice] = "ありがとうございました。またのご利用を心よりお待ちしております。"
    redirect_to root_path
  end

  private
  def end_user_params
    params.require(:end_user).permit(:first_name, :last_name, :kana_first_name, :kana_last_name, :address, :phone_number, :postal_code)
  end
  def end_use_is_working
    unless current_end_user.is_working
      redirect_to destroy_end_user_session_path
    end
  end

end

app/helpers/end_users_helper.rb
module EndUsersHelper
end

app/views/end_users/edit.html.erb
<div class="container">
<div class="mt-4 mb-5 small">
  <div class="m-5">
    <h2>新規会員登録</h2>
  </div>
  <%= form_for @end_user, url: end_users_path do |f| %>
    <div class="row form-group">
      <div class="col-1"></div>
      <div class="col-2">
        <p>名前</p>
      </div>
      <div class="col-1 text-right">
        <p class="">(姓)　</p>
      </div>
      <div class="col-2 pl-0">
        <%= f.text_field :first_name, autofocus: true, autocomplete: "first_name", class: 'form-control' %>
      </div>
      <div class="col-1 text-right">
        <p class="">(名)　</p>
      </div>
      <div class="field col-2 pl-0">
        <%= f.text_field :last_name, autocomplete: "last_name", class: 'form-control' %>
      </div>
    </div>

    <div class="row form-group align-bottom">
      <div class="col-1"></div>
      <div class="col-2">
        <p>フリガナ</p>
      </div>
      <div class="col-1 text-right">
        <p class="">(セイ)</p>
      </div>
      <div class="col-2 pl-0">
        <%= f.text_field :kana_first_name, autocomplete: "kana_first_name", class: 'form-control' %>
      </div>
      <div class="col-1 text-right">
        <p class="">(メイ)</p>
      </div>
      <div class="field col-2 pl-0">
        <%= f.text_field :kana_last_name, autocomplete: "kana_last_name", class: 'form-control' %>
      </div>
    </div>

    <div class="row form-group">
      <div class="col-1"></div>
      <div class="col-3">
        <p>メールアドレス</p>
      </div>
      <div class="field col-4 pl-0">
        <%= f.email_field :email, autocomplete: "email", class: 'form-control' %>
      </div>
    </div>

    <div class="row form-group">
      <div class="col-1"></div>
      <div class="col-3">
        <p>郵便番号(ハイフンなし)</p>
      </div>
      <div class="field col-4 pl-0">
        <%= f.text_field :address, autocomplete: "address", class: 'form-control' %>
      </div>
    </div>

    <div class="row form-group">
      <div class="col-1"></div>
      <div class="col-3">
        <p>住所</p>
      </div>
      <div class="field col-4 pl-0">
        <%= f.text_field :postal_code, autocomplete: "postal_code", class: 'form-control' %>
      </div>
    </div>

    <div class="row form-group">
      <div class="col-1"></div>
      <div class="col-3">
        <p>電話番号(ハイフンなし)</p>
      </div>
      <div class="field col-4 pl-0">
        <%= f.text_field :phone_number, autocomplete: "phone_number", class: 'form-control' %>
      </div>
    </div>

    <div class="text-center mt-3">
      <%= f.submit "編集内容を保存する", class: "btn btn-success px-5" %>
      <%= link_to "退会する", end_users_leave_user_path, class: "btn btn-danger" %>
    </div>
  <% end %>
</div>
</div>

app/views/end_users/leave_user.html.erb
<div class="continer text-center">
  <div class="mt-5">
    <strong>本当に退会しますか？</strong>
    <p class="my-4">退会すると、会員登録情報や<br>これまでの購入履歴が閲覧できなくなります。<br>退会する場合は、「退会する」をクリックしてください。</p>
  </div>
  <div class="text-center">
      <%= link_to "退会しない", end_users_path, class: "btn btn-info" %>
      <%= link_to "退会", end_users_leave_path, method: :patch, "data-confirm" => "本当に退会しますか？", class: "btn btn-danger" %>
    </div>
</div>

app/views/end_users/show.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col-8">
      <div class="row mb-3">
        <div class="col-2">登録情報</div>
        <div class="col-2">
          <%= link_to "編集する", edit_end_users_path, class: "btn btn-info" %>
        </div>
        <div class="col-3">
          <a href="#" class="btn btn-info">パスワードを変更する</a>
        </div>
      </div>
      <table class="table table-bordered">
        <tbody>
            <tr>
              <th scope="row">氏名</th>
              <td><%= @end_user.first_name %> <%= @end_user.last_name %></td>
            </tr>
            <tr>
              <th scope="row">カナ</th>
              <td><%= @end_user.kana_first_name %> <%= @end_user.kana_last_name %></td>
            </tr>
            <tr>
              <th scope="row">郵便番号</th>
              <td><%= @end_user.address %></td>
            </tr>
            <tr>
              <th scope="row">住所</th>
              <td><%= @end_user.postal_code %></td>
            </tr>
            <tr>
              <th scope="row">電話番号</th>
              <td><%= @end_user.phone_number %></td>
            </tr>
            <tr>
              <th scope="row">メールアドレス</th>
              <td><%= @end_user.email %></td>
            </tr>
        </tbody>
      </table>
      <div class="row mt-4">
        <div class="col-2">配送先</div>
        <div class="col-3">
          <%= link_to "一覧を見る", addresses_path, class: "btn btn-info" %>
        </div>
    　</div>
      <div class="row mt-3">
        <div class="col-2">注文履歴</div>
        <div class="col-3">
          <%= link_to "一覧を見る", orders_path, class: "btn btn-info" %>
        </div>
    　</div>　
    </div>
  </div>
</div>