config/routes.rb
Rails.application.routes.draw do

  resource :end_users, only: [:show, :edit, :update]
  get 'end_users/leave_user'
  patch "end_users/leave" => "end_users#leave"
  root 'items#top'
  resources :items, only: [:index, :show]
  devise_for :end_users, controllers: {   
    registrations: 'end_users/registrations',
    sessions: 'end_users/sessions' 
  }
  resources :cart_items, only: [:index, :create, :update, :destroy]
  delete "cart_items" => "cart_items#all_destroy", as: 'cart_items_all_destroy'

  get "orders/end"
  resources :orders, only: [:new, :index, :create, :show]
  post "orders/check"
  resources :addresses, only: [:index, :edit, :create, :update, :destroy]

  devise_for :admin, controllers: {
    sessions: 'admin/sessions'
  }
  namespace :admin do
    get "top", :to=>"items#top"
    resources :items
    resources :end_users, only: [:index, :show, :update, :edit]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :orders, only: [:index, :update, :show] do
      resources :order_details, only: [:update]
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="js/mdb.min.js"></script>
    <script type="text/javascript" src="https://code.jquery.com/ui/1.12.0/jquery-ui.min.js"></script>
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.12.1/themes/pepper-grinder/jquery-ui.css">
  </head>

  <nav class="navbar navbar-expand-md  navbar-light bg-info">
  <% if admin_signed_in? %>
    <a class="navbar-brand text-light" href="/admin/top">NagoyaCake</a>
  <% else %>
    <a class="navbar-brand text-light" href="/">NagoyaCake</a>
  <% end %>
    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#bs-navi" aria-controls="bs-navi" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="bs-navi">
      <% if end_user_signed_in? %>
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to(items_path, class: 'nav-link text-light') do %>
              商品一覧
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to( end_users_path, class: 'nav-link text-light') do %>
              マイページ
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to( cart_items_path, class: 'nav-link text-light') do %>
              カート
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to(destroy_end_user_session_path, method: :delete, class: 'nav-link text-light') do %>
              ログアウト
            <% end %>
          </li>
        </ul>
      <% elsif admin_signed_in? %>
        <div class="row">
        <div class="col-12">
        <ul class="navbar-nav text-light">
          <li class="nav-item">
            <%= link_to(admin_items_path, class: 'nav-link text-light') do %>
              商品一覧
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to( admin_end_users_path, class: 'nav-link text-light') do %>
              会員一覧
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to( admin_orders_path, class: 'nav-link text-light') do %>
              注文履歴一覧
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to( admin_genres_path, class: 'nav-link text-light') do %>
              ジャンル一覧
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to(destroy_admin_session_path, method: :delete, class: 'nav-link text-light') do %>
              ログアウト
            <% end %>
          </li>
        </ul>
        </div>
        </div>
            <div class="col-3">
              <%= form_tag(admin_items_path, :method => "get") do %>
                <div class="input-group input-group-sm">
                  <%= text_field_tag :search, params[:search], class:" form-control" %>
                  <%= submit_tag "検索", :name => nil , class: "input-group-btn btn btn-sm"%>
                </div>
              <% end %>
            </div>
      <% else %>
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to(items_path, class: 'nav-link text-light') do %>
              商品一覧
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to( new_end_user_registration_path, class: 'nav-link text-light') do %>
              新規登録
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to(new_end_user_session_path, class: 'nav-link text-light') do %>
              ログイン
            <% end %>
          </li>
        </ul>
      <% end %>
    </div>
  </nav>
<body>
  <%= yield %>
</body>

</html>